In [1]:
print("hello world")

hello world

In [2]:
import pandas as pd
import numpy as np

In [3]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url)

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
"Monal".replace("M","AA")

'AAonal'

In [6]:
df['Name'].str.replace('Mr.','Sir',regex=False).head()

0                              Braund, Sir Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Sir William Henry
Name: Name, dtype: str

In [ ]:
df['Name'].head()

In [ ]:
df.loc[1]['Name']

In [ ]:
df.loc[1,'Name']

In [ ]:
start = df.loc[1,'Name'].find("(")

In [ ]:
end = df.loc[1,'Name'].find(")")

In [ ]:
(df.loc[1,'Name'][0:start] + df.loc[1,'Name'][end +1 :]).rstrip()

In [ ]:
def replace_substr(Name):
    start = Name.find("(")
    end = Name.find(")")
    return (Name[0:start] + Name[end + 1:]).strip()

In [ ]:
df['Name_trim'] = df['Name'].apply(replace_substr)

In [ ]:
df['Name']

In [ ]:
df.loc[1,'Name_trim']

In [ ]:
# replace substrings with Regex : regular expression  * means zero more, .(dot) means match all characters r tells that its a raw string
# "\(.*\)"

df['Name'].str.replace(r"\(.*\)","Hello",regex=True).head()

In [ ]:
import re

def is_valid_email(email):
    """
    Validates an email address using a basic regular expression pattern.
    """
    # The pattern checks for a standard email format: user@domain.tld
    # It allows letters, numbers, periods, underscores, pluses, and hyphens
    # in the username and domain parts, and a 2+ character TLD.
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    
    # Use re.fullmatch() to ensure the entire string matches the pattern.
    # re.match() would only check from the beginning of the string.
    if re.fullmatch(pattern, email):
        return True
    else:
        return False

In [ ]:
# --- Example Usage ---
test_emails = [
    "user@example.com",
    "first.last+tag123@sub.domain-name.org",
    "invalid-email",
    "user@.com",
    "user@domain",
    "vinod@gmail.com",
    "@aarohi@gmail.com"
]

In [ ]:
for email in test_emails:
    if is_valid_email(email):
        print(f"'{email}' is a valid email address.")
    else:
        print(f"'{email}' is NOT a valid email address.")

In [ ]:
df['Name'][0]

In [ ]:
r_mr = df['Name'].str.split(",")[0]

In [ ]:
r_mr[1]

In [ ]:
r_mr

In [ ]:
df['Name'].str.split().str[0]

In [ ]:
df['Name'].str.strip()

In [ ]:
df['Name'].str.lstrip()

In [ ]:
df['Name'].str.rstrip()

In [ ]:
df['Name'].str.find('Mr')

In [ ]:
df['Name'].str.contains('Miss')

In [ ]:
df['Name'].str.contains('Miss').sum()

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name' : ['John Doe','Jane Smith','Emily Johnson','Robert Brown','Anna-Marie Lee'],
    'Email' : ['john@example.com','jane.smith@work.org','emily_j@data.net','robertb@yahoo.com','anna.lee@company.co']
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df.head()

             Name                Email
0        John Doe     john@example.com
1      Jane Smith  jane.smith@work.org
2   Emily Johnson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [6]:
df['Name'].str.pad(width=20,side='left',fillchar='_')

0    ____________John Doe
1    __________Jane Smith
2    _______Emily Johnson
3    ________Robert Brown
4    ______Anna-Marie Lee
Name: Name, dtype: str

In [7]:
class_data = {
    "Name": ["A","B","C","D"],
    "Groups" : ["G1","G2","G3","G4"]
}

In [8]:
df = pd.DataFrame(class_data)

In [9]:
df.head()

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [12]:
df[df['Groups'] > 'G4']

Empty DataFrame
Columns: [Name, Groups]
Index: []

In [16]:
# G3 - G1 - G2 -G4
df['Groups_cat']= pd.Categorical(
    df['Groups'],
    categories=['G3','G1','G2','G4'],  # custom order(ascending)
    ordered=True
)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      str
 1   Groups      4 non-null      str
 2   Groups_cat  4 non-null      category
dtypes: category(1), str(2)
memory usage: 404.0 bytes

In [18]:
df['Groups_cat'].cat.categories

Index(['G3', 'G1', 'G2', 'G4'], dtype='str')

In [24]:
df['Groups_cat'] >= 'G4'

0    False
1    False
2    False
3     True
Name: Groups_cat, dtype: bool

In [25]:
class_data

{'Name': ['A', 'B', 'C', 'D'], 'Groups': ['G1', 'G2', 'G3', 'G4']}

In [26]:
df

  Name Groups Groups_cat
0    A     G1         G1
1    B     G2         G2
2    C     G3         G3
3    D     G4         G4

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [32]:
df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [35]:
df['Embarked'] = df['Embarked'].fillna("N")

In [36]:
df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [37]:
df['Embarked_auto_cat'] = df['Embarked'].astype('category')

In [38]:
df['Embarked_auto_cat'].cat.categories

Index(['C', 'N', 'Q', 'S'], dtype='str')

In [40]:
# G3 - G1 - G2 -G4
df['Embarked_auto_cat']= pd.Categorical(
    df['Embarked'],
    categories=['N','S','C','Q'],  # custom order(ascending)
    ordered=True
)

In [41]:
df['Embarked_auto_cat'].cat.categories

Index(['N', 'S', 'C', 'Q'], dtype='str')

In [42]:
df['Embarked_auto_cat'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked_auto_cat, dtype: category
Categories (4, str): ['N' < 'S' < 'C' < 'Q']

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PassengerId        891 non-null    int64
 1   Survived           891 non-null    int64
 2   Pclass             891 non-null    int64
 3   Name               891 non-null    str
 4   Sex                891 non-null    str
 5   Age                714 non-null    float64
 6   SibSp              891 non-null    int64
 7   Parch              891 non-null    int64
 8   Ticket             891 non-null    str
 9   Fare               891 non-null    float64
 10  Cabin              204 non-null    str
 11  Embarked           891 non-null    str
 12  Embarked_auto_cat  891 non-null    category
dtypes: category(1), float64(2), int64(5), str(5)
memory usage: 84.7 KB

In [53]:
def encode(Sex):
    return (0 if Sex=='male' else 1)

In [55]:
encode('male')

0

In [56]:
df['Sex'] = df['Sex'].apply(lambda Sex: 1 if Sex=='male' else 0)

In [58]:
df['Sex'].head(10)

0    1
1    0
2    0
3    0
4    1
5    1
6    1
7    1
8    0
9    0
Name: Sex, dtype: int64

In [60]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Embarked_auto_cat
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S,S
5,6,0,3,"Moran, Mr. James",1,NaN,0,0,330877,8.4583,NaN,Q,Q
6,7,0,1,"McCarthy, Mr. Timothy J",1,54.0,0,0,17463,51.8625,E46,S,S
7,8,0,3,"Palsson, Master. Gosta Leonard",1,2.0,3,1,349909,21.0750,NaN,S,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",0,27.0,0,2,347742,11.1333,NaN,S,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",0,14.0,1,0,237736,30.0708,NaN,C,C

In [62]:
df['Sex_cat'] = df['Sex'].astype('category').cat.codes

In [63]:
df['Sex_cat']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex_cat, Length: 891, dtype: int8

In [64]:
df['Sex_cat1'] = df['Sex'].replace(['female','male'],[0,1])

In [65]:
df['Sex_cat1']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex_cat1, Length: 891, dtype: int64

In [5]:
df = pd.DataFrame({
    
    'event': ['Concert','Conference','Wedding'],
    'date' : ['2025-01-01','2025-03-15','2025-07-20']
})

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   event   3 non-null      str
 1   date    3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [8]:
df

        event        date
0     Concert  2025-01-01
1  Conference  2025-03-15
2     Wedding  2025-07-20

In [9]:
df['date_pandas'] = pd.to_datetime(df['date'])

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event        3 non-null      str
 1   date         3 non-null      str
 2   date_pandas  3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [11]:
df.head()

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15
2     Wedding  2025-07-20  2025-07-20

In [12]:
df['date_pandas'].dt.year

0    2025
1    2025
2    2025
Name: date_pandas, dtype: int32

In [13]:
df['date_pandas'].dt.month

0    1
1    3
2    7
Name: date_pandas, dtype: int32

In [14]:
df['date_pandas'].dt.day

0     1
1    15
2    20
Name: date_pandas, dtype: int32

In [15]:
df['date_pandas'].dt.weekday

0    2
1    5
2    6
Name: date_pandas, dtype: int32

In [16]:
df['date_pandas'].dt.day

0     1
1    15
2    20
Name: date_pandas, dtype: int32

In [18]:
df['date_pandas'].dt.day_name()

0    Wednesday
1     Saturday
2       Sunday
Name: date_pandas, dtype: str

In [19]:
df[df['date_pandas'] > '2025-04-01']

     event        date date_pandas
2  Wedding  2025-07-20  2025-07-20

In [20]:
df[df['date_pandas'].between('2025-01-01','2025-06-01')]

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15

In [22]:
pd.date_range(start='2026-02-01',end='2026-02-10',freq='D')

DatetimeIndex(['2026-02-01', '2026-02-02', '2026-02-03', '2026-02-04',
               '2026-02-05', '2026-02-06', '2026-02-07', '2026-02-08',
               '2026-02-09', '2026-02-10'],
              dtype='datetime64[us]', freq='D')

In [23]:
pd.date_range(start='2024-01-01',end='2024-03-10',freq='ME')

DatetimeIndex(['2024-01-31', '2024-02-29'], dtype='datetime64[us]', freq='ME')

In [24]:
pd.date_range(start='2024-01-01',end='2024-03-10',freq='MS')

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01'], dtype='datetime64[us]', freq='MS')

In [27]:
df['next_week'] = df['date_pandas'] + pd.Timedelta(days=7)

In [28]:
df['next_week']

0   2025-01-08
1   2025-03-22
2   2025-07-27
Name: next_week, dtype: datetime64[us]

In [29]:
df.head()

        event        date date_pandas  next_week
0     Concert  2025-01-01  2025-01-01 2025-01-08
1  Conference  2025-03-15  2025-03-15 2025-03-22
2     Wedding  2025-07-20  2025-07-20 2025-07-27

In [31]:
df['days_to_event'] = df['date_pandas'] - pd.Timestamp.today()

In [32]:
df['days_to_event']

0   -426 days +04:59:43.343148
1   -353 days +04:59:43.343148
2   -226 days +04:59:43.343148
Name: days_to_event, dtype: timedelta64[us]

In [33]:
df.head()

        event        date date_pandas  next_week              days_to_event
0     Concert  2025-01-01  2025-01-01 2025-01-08 -426 days +04:59:43.343148
1  Conference  2025-03-15  2025-03-15 2025-03-22 -353 days +04:59:43.343148
2     Wedding  2025-07-20  2025-07-20 2025-07-27 -226 days +04:59:43.343148

# added few lines of code